export const FAQ_DEFAULT = {
  General: [['What solutions does iGo Green Energy provide?', 'Solar energy, wind energy, biogas solutions and water treatment, all under one roof.'], ['What makes iGo Green Energy different?', 'It is one of the few companies offering solar, wind, biogas, and water treatment solutions together, giving customers a single trusted partner with no need to manage multiple vendors.'], ['Who does iGo Green Energy serve?', 'Residential, commercial, industrial, agriculture and dairy, and government and institutional customers.']],
  Solar: [['Do you provide residential, commercial and industrial solar?', 'Yes. iGo Green Energy provides solar solutions for all three segments.'], ['What system types and capacities do you offer?', 'On-grid, off-grid and hybrid systems, from 1 kW to 5 MW and above.'], ['Do you provide design and consultation?', 'Yes: site assessment, energy-needs analysis, and system design.'], ['Do you provide installation and commissioning?', 'Yes, carried out by certified installation partners and managed by our project team from start to finish.'], ['Do you provide AMC?', 'Yes. We offer both one-time maintenance and annual maintenance contracts.'], ['Do you help with subsidies?', 'Yes. We assist with subsidy applications, net metering, approvals and documentation. Availability and eligibility depend on current government policy and customer category.'], ['What equipment do you use?', 'Tier-1 certified equipment from leading manufacturers, including solar panels, inverters, batteries, and mounting and electrical components.'], ['What warranty is provided?', 'Manufacturer warranties on major components plus our own workmanship warranty. Warranty periods and terms vary by product and are shared with every quotation.']],
  Wind: [['Do you provide wind EPC?', 'Yes. We deliver complete turnkey EPC (Engineering, Procurement, and Construction) for wind projects, from design to commissioning.'], ['Do you provide O&M?', 'Yes: preventive maintenance, corrective maintenance and full O&M contracts.'], ['What turbine capacity ranges do you support?', 'Small wind turbines up to 100 kW and utility-scale turbines from 1 MW to 3 MW and above.'], ['Do you provide feasibility studies?', 'Yes: wind resource assessment, site evaluation, and technical and financial feasibility.'], ['Which regions do you serve?', 'Pan-India, in all states with good wind potential.']],
  Biogas: [['What plant capacities do you handle?', 'From 1–10 m³/day up to large-scale CBG above 1,000 m³/day.'], ['Do you provide design and engineering?', 'Yes. Design and engineering are delivered through technical partners.'], ['Do you provide turnkey installation?', 'Yes. Full turnkey installation and commissioning.'], ['Do you provide AMC?', 'Yes. Operation and maintenance services are provided through annual maintenance contracts.'], ['Which industries can use biogas?', 'Agriculture and dairy farms, food processing and distilleries, municipal and urban waste, hotels, hospitals and institutions, and poultry and meat processing.'], ['What warranty and after-sales support are provided?', 'Warranty and after-sales terms will be provided once finalized.']],
  'Water Treatment': [['What water treatment systems do you provide?', 'Reverse Osmosis (RO) and demineralization systems.'], ['Do you provide RO?', 'Yes.'], ['Do you provide demineralization?', 'Yes.'], ['What project scale do you handle?', 'Medium-scale projects, from 10 to 100 KLD.'], ['Do you provide customized solutions?', 'Yes. Solutions are customized based on water quality analysis.'], ['Do you provide installation and maintenance?', 'Yes. Design, installation, commissioning and maintenance are all provided.']],
  Projects: [['Can I see your completed projects?', 'iGo Green Energy is a newly launched brand. Completed solar and wind project details will be added as projects are delivered. Details of completed biogas and water treatment projects are confidential and cannot be shared.'], ['Can I filter projects by service?', 'Yes. The Projects page has filters for Solar, Wind, Biogas and Water Treatment.']],
  'Testimonials / Clients': [['Do you have customer testimonials?', 'Client stories will be shared on the Testimonials / Clients page once they are ready.']],
  Services: [['Do you have separate pages for each service?', 'Yes. Solar, Wind, Biogas and Water Treatment each have their own page.'], ['How does the process start?', 'With a consultation or site survey. Request a Smart Quote and our team will take it from there.']],
};
